Repository yeeezsh/FluentSearch-FE, pull requests merged in 2020-11, with the labels that each got.

#13 Add style-component Dependency
  .babelrc
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: approved, dependency changed

#14 Docker integration
  .dockerignore
  .eslintignore
  .github/workflows/ci.yml
  .github/workflows/dockerhub.yml
  Dockerfile
  next.config.js
  package.json
  server/nginx.conf
Labels: enhancement, in progress

#16 Update dockerhub.yml
  .github/workflows/dockerhub.yml
Labels: approved

#17 Add Enzyme Dependency
  package.json
  yarn.lock
Labels: dependency changed

#19 Fix Jest
  .babelrc
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  Dockerfile
  __mock__/fileMock.js
  __test__/.gitkeep
  __test__/pages/.gitkeep
  __test__/pages/__snapshots__/index.spec.tsx.snap
  __test__/pages/index.spec.tsx
  babel.config.js
  components/Button/Button.spec.tsx
  jest.config.js
  jest.setup.ts
  next.config.js
  package.json
  pages/index.tsx
  setupTests.js
  tsconfig.jest.json
  tsconfig.json
  utils/path-join.ts
  yarn.lock
Labels: dependency changed, in progress
